#################################
# Predictions
#################################
Predictions:
  # Perturbative order, 0: LO, 1: NLO 2: NNLO
  perturbative order: 2

  # Initial scale in GeV to be used for the DGLAP evolution of the FFs.
  mu0: 1

  # Quark thresholds
  thresholds: [0, 0, 0, 1.51, 4.92]

  # Strong coupling
  alphas:
    aref: 0.118
    Qref: 91.1876

  # APFEL++ grid
  xgrid:
    - [200, 1e-5, 3]
    - [100, 1e-1, 3]
    - [80,  8e-1, 3]

  ###################
  # Replica settings
  ###################
  # 
  # Here you can choose how replicas in the unpolarised PDF and FF
  # sets are used in the analysis.
  #  0: The central replica (mean value) is chosen for both
  #     unpolarised PDF and FF sets, overwriting the values
  #     provided below.
  # -1: PDF and FF replicas are chosen randomly, overwriting
  #     the values provided below.
  #  1: The values provided below are used to select a particular
  #     replica in the set.
  # If the fit is performed with unfluctuated data ("./optimise 0"), option 0
  # is automatically adopted.
  Replica settings: -1

  ##############
  # Positivity
  ##############
  # Here you can select how the positivity constraint is 
  # implemented. 
  #   false:  the positivity bound is imposed with a unpolarised 
  #           PDF replica selected randomly from the set.
  #    true:  the positivity bound is imposed through the central
  #           replica of the unpolarised PDF set inflated by a 
  #           factor specified in "Multiplicative factor".
  Include Std: false
  #Multiplicative factor: 5

  # List of external sets to be used in the analysis.
  #   name: is the number of the PDF set as provided in 
  #         the LHAPDF list.
  # member: replica member to be used in the analysis.
  #         This key is overwritten if 'Replica settings'
  #         is either set to 0 or -1.
  Sets:
    # Unpolarised PDF set
    unpolarised pdfset:
      name: NNPDF31_nnlo_pch_as_0118
      member: -1 #N>=0 for a specific member (0 for central)

    # FF sets
    PIplus ffset:
      name: MAPFF10NNLOPIp
      member: -1

    PIminus ffset:
      name: MAPFF10NNLOPIm
      member: -1

    KAplus ffset:
      name: MAPFF10NNLOKAp
      member: -1

    KAminus ffset:
      name: MAPFF10NNLOKAm
      member: -1

    #HAplus ffset:
    #  name: MAPFF10NNLOHAp
    #  member: -1

    #HAminus ffset:
    #  name: MAPFF10NNLOHAm
    #  member: -1

#################################
# Optimiser
#################################
# Parameters of the optimiser managed by ceres-solver
Optimizer:
  max_num_iterations: 3000

  chi2_tolerance: 3

#################################
# NNAD
#################################
NNAD:
  # Initialisation seed
  seed: 0

  # Flavour map
  # Available flavour maps:
  # - "separate sbar" (0): sbar, ubar, dbar, g, d, u, s
  # - "s=sbar"        (1): ubar, dbar, g, u, d, s = sbar.
  flavour map: 0

  # Architecture
  # DO NOT MODIFY THE INPUT
  # The output must be consistent with the flavour map:
  # - "separate sbar" : 7
  # - "s=sbar" : 6
  architecture: [1, 10, 7]


#################################
# Data
#################################
Data:
  # Seed used for the replica generation and the splitting between
  # training and validation (do not use a too large number here in
  # order to avoid correlation in the replica generation).
  seed: 2

  # Minimum number of points below which all points will be included in the training.
  # If not provided, Denali sets this number to 10.
  minimum training size: 10

  # Datasets to be included in the fit along with specific cuts and
  # traning fraction. Each single dataset can implement an arbitrary
  # number of cuts determined by the name of the appropriate function
  # (e.g. xcut) and the allowed range.
  sets:
  - {name: "COMPASS KA^- A_1^p",         file: "COMPASS_A1P_KA_MINUS.yaml",        cuts: [{name: Qcut, min: 1, max: 100}], training fraction: 0.8}
  - {name: "COMPASS KA^+ A_1^p",         file: "COMPASS_A1P_KA_PLUS.yaml",         cuts: [{name: Qcut, min: 1, max: 100}], training fraction: 0.8}
  - {name: "COMPASS PI^- A_1^p",         file: "COMPASS_A1P_PI_MINUS.yaml",        cuts: [{name: Qcut, min: 1, max: 100}], training fraction: 0.8}
  - {name: "COMPASS PI^+ A_1^p",         file: "COMPASS_A1P_PI_PLUS.yaml",         cuts: [{name: Qcut, min: 1, max: 100}], training fraction: 0.8}
  - {name: "COMPASS KA^- A_1^d",         file: "COMPASS_A1D_KA_MINUS.yaml",        cuts: [{name: Qcut, min: 1, max: 100}], training fraction: 0.8}
  - {name: "COMPASS KA^+ A_1^d",         file: "COMPASS_A1D_KA_PLUS.yaml",         cuts: [{name: Qcut, min: 1, max: 100}], training fraction: 0.8}
  - {name: "COMPASS PI^- A_1^d",         file: "COMPASS_A1D_PI_MINUS.yaml",        cuts: [{name: Qcut, min: 1, max: 100}], training fraction: 0.8}
  - {name: "COMPASS PI^+ A_1^d",         file: "COMPASS_A1D_PI_PLUS.yaml",         cuts: [{name: Qcut, min: 1, max: 100}], training fraction: 0.8}
  - {name: "HERMES 2018 KA^- A_1^d",     file: "HERMES_2018_A1D_KA_MINUS.yaml",    cuts: [{name: Qcut, min: 1, max: 100}], training fraction: 0.8}
  - {name: "HERMES 2018 KA^+ A_1^d",     file: "HERMES_2018_A1D_KA_PLUS.yaml",     cuts: [{name: Qcut, min: 1, max: 100}], training fraction: 0.8}
  - {name: "HERMES 2018 PI^- A_1^d",     file: "HERMES_2018_A1D_PI_MINUS.yaml",    cuts: [{name: Qcut, min: 1, max: 100}], training fraction: 0.8}
  - {name: "HERMES 2018 PI^+ A_1^d",     file: "HERMES_2018_A1D_PI_PLUS.yaml",     cuts: [{name: Qcut, min: 1, max: 100}], training fraction: 0.8}
  - {name: "HERMES 2018 PI^- A_1^p",     file: "HERMES_2018_A1P_PI_MINUS.yaml",    cuts: [{name: Qcut, min: 1, max: 100}], training fraction: 0.8}
  - {name: "HERMES 2018 PI^+ A_1^p",     file: "HERMES_2018_A1P_PI_PLUS.yaml",     cuts: [{name: Qcut, min: 1, max: 100}], training fraction: 0.8}
  - {name: "E142 g_1^N",                 file: "E142_G1N.yaml",                    cuts: [{name: Wcut, min: 2.5495, max: 100}, {name: Qcut, min: 1, max: 100}], training fraction: 0.8}
  - {name: "E143 g_1^D",                 file: "E143_G1D.yaml",                    cuts: [{name: Wcut, min: 2.5495, max: 100}, {name: Qcut, min: 1, max: 100}], training fraction: 0.8}
  - {name: "E143 g_1^P",                 file: "E143_G1P.yaml",                    cuts: [{name: Wcut, min: 2.5495, max: 100}, {name: Qcut, min: 1, max: 100}], training fraction: 0.8}
  - {name: "E154 g_1^N",                 file: "E154_G1N.yaml",                    cuts: [{name: Wcut, min: 2.5495, max: 100}, {name: Qcut, min: 1, max: 100}], training fraction: 0.8}
  - {name: "E155 g_1^P/F_1^P",           file: "E155_G1P_F1P.yaml",                cuts: [{name: Wcut, min: 2.5495, max: 100}, {name: Qcut, min: 1, max: 100}], training fraction: 0.8}
  - {name: "E155 g_1^N/F_1^N",           file: "E155_G1N_F1N.yaml",                cuts: [{name: Wcut, min: 2.5495, max: 100}, {name: Qcut, min: 1, max: 100}], training fraction: 0.8}
  - {name: "EMC g_1^P",                  file: "EMC_G1P.yaml",                     cuts: [{name: Wcut, min: 2.5495, max: 100}, {name: Qcut, min: 1, max: 100}], training fraction: 0.8}
  - {name: "JLAB E06 014 g_1^N/F_1^N",   file: "JLAB_E06_014_G1N_F1N.yaml",        cuts: [{name: Wcut, min: 2.5495, max: 100}, {name: Qcut, min: 1, max: 100}], training fraction: 0.8}
  - {name: "JLAB E97 103 g_1^N",         file: "JLAB_E97_103_G1N.yaml",            cuts: [{name: Wcut, min: 2.5495, max: 100}, {name: Qcut, min: 1, max: 100}], training fraction: 0.8}
  - {name: "JLAB E99 117 g_1^N/F_1^N",   file: "JLAB_E99_117_G1N_F1N.yaml",        cuts: [{name: Wcut, min: 2.5495, max: 100}, {name: Qcut, min: 1, max: 100}], training fraction: 0.8}
  - {name: "JLAB EG1 DVCS G_1^D/F_1^D",  file: "JLAB_EG1_DVCS_G1D_F1D.yaml",       cuts: [{name: Wcut, min: 2.5495, max: 100}, {name: Qcut, min: 1, max: 100}], training fraction: 0.8}
  - {name: "JLAB EG1 DVCS G_1^P/F_1^P",  file: "JLAB_EG1_DVCS_G1P_F1P.yaml",       cuts: [{name: Wcut, min: 2.5495, max: 100}, {name: Qcut, min: 1, max: 100}], training fraction: 0.8}
  - {name: "SMC g_1^D",                  file: "SMC_G1D.yaml",                     cuts: [{name: Wcut, min: 2.5495, max: 100}, {name: Qcut, min: 1, max: 100}], training fraction: 0.8}
  - {name: "SMC g_1^P",                  file: "SMC_G1P.yaml",                     cuts: [{name: Wcut, min: 2.5495, max: 100}, {name: Qcut, min: 1, max: 100}], training fraction: 0.8}
  - {name: "COMPASS g_1^D",              file: "COMPASS_G1D.yaml",                 cuts: [{name: Wcut, min: 2.5495, max: 100}, {name: Qcut, min: 1, max: 100}], training fraction: 0.8}
  - {name: "COMPASS g_1^P",              file: "COMPASS_G1P.yaml",                 cuts: [{name: Wcut, min: 2.5495, max: 100}, {name: Qcut, min: 1, max: 100}], training fraction: 0.8}
  - {name: "HERMES g_1^N",               file: "HERMES_G1N.yaml",                  cuts: [{name: Wcut, min: 2.5495, max: 100}, {name: Qcut, min: 1, max: 100}], training fraction: 0.8}
  - {name: "HERMES g_1^D",               file: "HERMES_G1D.yaml",                  cuts: [{name: Wcut, min: 2.5495, max: 100}, {name: Qcut, min: 1, max: 100}], training fraction: 0.8}
  - {name: "HERMES g_1^P",               file: "HERMES_G1P.yaml",                  cuts: [{name: Wcut, min: 2.5495, max: 100}, {name: Qcut, min: 1, max: 100}], training fraction: 0.8}
  - {name: "a3 sum rule",                file: "sum_rule_a3.yaml",                 cuts: [], training fraction: 1}
  - {name: "a8 sum rule",                file: "sum_rule_a8.yaml",                 cuts: [], training fraction: 1}